# Generated by Django 4.2.3 on 2023-07-09 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedme', '0002_feed_alter_user_id_user_reccomendations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='content',
            new_name='description',
        ),
    ]
