# Generated by Django 4.2.3 on 2023-07-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedme', '0003_rename_content_feed_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='image',
            field=models.TextField(default='image_url'),
            preserve_default=False,
        ),
    ]
