# Generated by Django 4.2.3 on 2023-07-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedme', '0004_feed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='category',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feed',
            name='keywords',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
