# Generated by Django 4.2.3 on 2023-07-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedme', '0005_feed_category_feed_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feed_history',
            field=models.ManyToManyField(related_name='feed_history', to='feedme.feed'),
        ),
        migrations.AddField(
            model_name='user',
            name='keywords',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='reccomendations',
            field=models.ManyToManyField(related_name='recommendations', to='feedme.feed'),
        ),
    ]
