# Generated by Django 4.2.3 on 2023-07-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedme', '0008_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
