# Generated by Django 4.2.3 on 2023-07-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedme', '0009_alter_user_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='keywords',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
